/* global window */
// Mock data for Scuffers Control Tower

window.SCUFFERS_DATA = {
  launch: {
    name: "DROP 04 — ECRU CAPSULE",
    code: "DRP-04-ECR",
    started: "T+02:14:08",
    status: "EN VIVO / ALTA PRESIÓN",
    units_total: 1840,
    units_sold: 1247,
    revenue: "€ 184,920",
    aov: "€ 148.30",
    sessions: 28412,
    cvr: "4.39%",
  },

  kpis: [
    { k: "Riesgos activos", v: 17, delta: "+5 últimos 5 min", tone: "crit" },
    { k: "SKUs críticos", v: 4, delta: "de 22 monitorizados", tone: "crit" },
    { k: "Tickets urgentes", v: 9, delta: "+3 últimos 10 min", tone: "hot" },
    { k: "VIPs impactados", v: 6, delta: "3 sin resolver", tone: "hot" },
    { k: "Campañas en revisión", v: 3, delta: "1 sobre presupuesto", tone: "" },
    { k: "Confianza", v: "0.86", delta: "modelo · drop-04", tone: "brand" },
  ],

  summary: [
    { type: "text", value: "Drop 04 lleva " },
    { type: "strong", value: "2h 14m" },
    { type: "text", value: " en vivo. Ritmo de venta " },
    { type: "amber", value: "23% por encima" },
    { type: "text", value: " del forecast. " },
    { type: "red", value: "HOODIE-BLK-M" },
    { type: "text", value: " agotándose en Madrid antes de cubrir tickets VIP. Campaña " },
    { type: "red", value: "CMP-778" },
    { type: "text", value: " sigue empujando ese SKU. " },
    { type: "amber", value: "Express shipping" },
    { type: "text", value: " saturado para 23 pedidos. Soporte con " },
    { type: "amber", value: "9 tickets" },
    { type: "text", value: " urgentes, 3 de clientes top." },
  ],

  actions: [
    {
      rank: 1,
      type: "PAUSE_CAMPAIGN",
      severity: "critical",
      title: "Pausar CMP-778 antes de agotar HOODIE-BLK-M en Madrid",
      reason: "Campaña empujando 14× tráfico sobre SKU con 7 unidades disponibles. Agotamiento estimado en 11 minutos.",
      pills: [
        { label: "stock < 8", tone: "crit" },
        { label: "campaña saturando", tone: "crit" },
        { label: "VIP en riesgo", tone: "vip" },
        { label: "MAD", tone: "" },
      ],
      confidence: 0.94,
      owner: "Resp. de marketing",
      automation: true,
      ackable: true,
      evidence: {
        items: [
          { l: "SKU", v: "HOODIE-BLK-M" },
          { l: "Stock", v: "7 u." },
          { l: "ETA agotamiento", v: "≈ 11 min" },
          { l: "Tráfico campaña", v: "14.2× baseline" },
          { l: "VIPs en cola", v: "3" },
          { l: "Spend last hour", v: "€ 2,140" },
        ],
        note: "Modelo: stock-pressure v3.2 · señal cruzada con campaign-intensity. Subió al top por colisión inventario × VIP × ritmo de quema.",
      },
    },
    {
      rank: 2,
      type: "ESCALATE_TICKET",
      severity: "critical",
      title: "Responder ticket #4821 — VIP TOP-50, pedido extraviado, 2h sin respuesta",
      reason: "Cliente con LTV €4,820 y 14 pedidos. Sentimiento muy negativo. Riesgo de churn público en redes.",
      pills: [
        { label: "VIP", tone: "vip" },
        { label: "urgent ticket", tone: "crit" },
        { label: "sentiment -0.82", tone: "crit" },
        { label: "social risk", tone: "hot" },
      ],
      confidence: 0.91,
      owner: "Resp. de soporte",
      automation: false,
      evidence: {
        items: [
          { l: "Ticket", v: "#4821" },
          { l: "Cliente", v: "M. Vázquez" },
          { l: "LTV", v: "€ 4,820" },
          { l: "Sentimiento", v: "-0.82" },
          { l: "Tiempo sin resp.", v: "2h 04m" },
          { l: "Pedido", v: "ORD-19483" },
        ],
        note: "Pico de menciones del username en X en última hora. Recomendado escalado humano + courtesy credit.",
      },
    },
    {
      rank: 3,
      type: "RESERVE_INVENTORY",
      severity: "high",
      title: "Reservar 12 u. de TEE-CRM-L para tickets de fulfillment pendientes",
      reason: "Bloque de 12 pedidos en cola con 3 VIPs. Stock cayendo a 18 u. y ritmo de venta de 4 u/min.",
      pills: [
        { label: "stock < 20", tone: "hot" },
        { label: "VIP", tone: "vip" },
        { label: "fulfillment", tone: "" },
      ],
      confidence: 0.87,
      owner: "Resp. de logística",
      automation: true,
      evidence: {
        items: [
          { l: "SKU", v: "TEE-CRM-L" },
          { l: "Stock", v: "18 u." },
          { l: "Pedidos en cola", v: "12" },
          { l: "Ritmo", v: "4 u/min" },
          { l: "VIPs en bloque", v: "3" },
        ],
        note: "Reserva soft de 12 u. para fulfillment queue ya configurada por defecto. Confirmar para ejecutar.",
      },
    },
    {
      rank: 4,
      type: "BOOST_SHIPPING",
      severity: "high",
      title: "Activar carrier secundario en MAD para pedidos express con SLA en riesgo",
      reason: "23 envíos express con SLA < 18h y cola del carrier principal saturada al 94%.",
      pills: [
        { label: "express", tone: "hot" },
        { label: "SLA en riesgo", tone: "hot" },
        { label: "MAD", tone: "" },
        { label: "23 pedidos", tone: "" },
      ],
      confidence: 0.83,
      owner: "Resp. de logística",
      automation: true,
      evidence: {
        items: [
          { l: "Pedidos afectados", v: "23" },
          { l: "Ciudad", v: "Madrid" },
          { l: "Carrier saturación", v: "94%" },
          { l: "SLA promedio", v: "16h 40m" },
          { l: "Coste delta carrier 2", v: "+ €1.80 / envío" },
        ],
        note: "Carrier secundario validado en drop anterior. Activación reversible.",
      },
    },
    {
      rank: 5,
      type: "LIMIT_CAMPAIGN",
      severity: "high",
      title: "Limitar gasto de CMP-651 — saturando audiencia BCN sin convertir",
      reason: "CTR cayendo 38% en última hora y CPA 2.4× sobre objetivo. Riesgo de fatiga creativa.",
      pills: [
        { label: "bajo rendimiento", tone: "hot" },
        { label: "BCN", tone: "" },
        { label: "CPA 2.4x", tone: "hot" },
      ],
      confidence: 0.79,
      owner: "Resp. de marketing",
      automation: true,
      evidence: {
        items: [
          { l: "Campaign", v: "CMP-651" },
          { l: "CTR Δ", v: "-38%" },
          { l: "CPA", v: "€ 38.20" },
          { l: "Spend last hour", v: "€ 1,420" },
          { l: "Frecuencia", v: "5.2" },
        ],
        note: "Recomendación: cap diario al 60%. Mantiene presencia sin quemar audiencia.",
      },
    },
    {
      rank: 6,
      type: "ESCALATE_TICKET",
      severity: "high",
      title: "Agrupar 4 tickets duplicados sobre fallo de checkout móvil iOS",
      reason: "4 tickets reportan error 402 al pagar con Apple Pay desde iOS 17.4. 38 sesiones afectadas detectadas en logs.",
      pills: [
        { label: "bug checkout", tone: "hot" },
        { label: "iOS", tone: "info" },
        { label: "38 sesiones", tone: "hot" },
      ],
      confidence: 0.81,
      owner: "Resp. de soporte",
      automation: false,
      evidence: {
        items: [
          { l: "Tickets", v: "#4815, #4818, #4823, #4825" },
          { l: "Plataforma", v: "iOS 17.4 / Safari" },
          { l: "Sesiones afectadas", v: "38" },
          { l: "Revenue blocked", v: "≈ €5,640" },
          { l: "Primer reporte", v: "T+01:42" },
        ],
        note: "Patrón confirmado por logs. Recomendado escalar a Engineering On-call y respuesta canned a clientes.",
      },
    },
    {
      rank: 7,
      type: "MONITOR_SKU",
      severity: "medium",
      title: "Monitorear PANT-NVY-32 — patrón de venta atípico vs. histórico",
      reason: "Sell-through 3.2× sobre forecast pero conversion 1.4×. Posible bot o coordinación.",
      pills: [
        { label: "anomalía", tone: "info" },
        { label: "monitorizar", tone: "info" },
      ],
      confidence: 0.68,
      owner: "Resp. de operaciones",
      automation: false,
      evidence: {
        items: [
          { l: "SKU", v: "PANT-NVY-32" },
          { l: "Sell-through", v: "3.2× forecast" },
          { l: "CVR", v: "8.7%" },
          { l: "Velocidad", v: "11 u/min" },
        ],
        note: "Señal aún no concluyente. Activar bot-check si supera 4× forecast.",
      },
    },
    {
      rank: 8,
      type: "RESPOND_TICKET",
      severity: "medium",
      title: "Confirmar reembolso parcial a 3 pedidos con incidencia de talla",
      reason: "Cluster de tickets sobre talla M de HOODIE-BLK reportada como pequeña. Solución estándar disponible.",
      pills: [
        { label: "problema talla", tone: "info" },
        { label: "auto-resolución", tone: "ok" },
      ],
      confidence: 0.74,
      owner: "Resp. de soporte",
      automation: true,
      evidence: {
        items: [
          { l: "Tickets", v: "3" },
          { l: "Total reembolso", v: "€ 137.40" },
          { l: "Política", v: "T-04 estándar" },
        ],
        note: "Reembolso parcial 30% + retención mediante crédito tienda. Pre-aprobado en política T-04.",
      },
    },
    {
      rank: 9,
      type: "MONITOR_CAMPAIGN",
      severity: "medium",
      title: "Verificar CMP-771 — performance dentro de banda pero spend alto",
      reason: "Gasto a un 78% del cap y 4h restantes. Cerca de límite pero todavía rentable.",
      pills: [
        { label: "monitorizar", tone: "info" },
        { label: "gasto 78%", tone: "" },
      ],
      confidence: 0.62,
      owner: "Resp. de marketing",
      automation: false,
      evidence: {
        items: [
          { l: "Campaign", v: "CMP-771" },
          { l: "Spend", v: "€ 4,290 / 5,500" },
          { l: "ROAS", v: "3.8" },
          { l: "Time left", v: "4h 11m" },
        ],
        note: "Sin acción inmediata. Re-evaluar en T+03:00.",
      },
    },
    {
      rank: 10,
      type: "RESOLVED",
      severity: "resolved",
      title: "BAG-ECR-OS — restock confirmado, presión normalizada",
      reason: "Stock pasó de 4 a 28 u. tras reposición de almacén central. Cola de wishlist notificada.",
      pills: [
        { label: "resuelto", tone: "ok" },
        { label: "auto", tone: "ok" },
      ],
      confidence: 0.98,
      owner: "Resp. de logística",
      automation: true,
      evidence: {
        items: [
          { l: "SKU", v: "BAG-ECR-OS" },
          { l: "Stock antes", v: "4 u." },
          { l: "Stock ahora", v: "28 u." },
          { l: "Wishlist notif.", v: "142" },
        ],
        note: "Acción ejecutada automáticamente. Marcada como resuelta T+02:08.",
      },
    },
  ],

  radar: [
    { name: "Inventario", value: "ALTO", level: 78, tone: "crit", note: "4 SKUs críticos · HOODIE-BLK-M lidera presión" },
    { name: "Soporte", value: "ALTO", level: 64, tone: "hot", note: "9 tickets urgentes · 3 VIPs sin respuesta" },
    { name: "Logística", value: "MEDIO", level: 52, tone: "hot", note: "Carrier MAD al 94% · 23 envíos en SLA" },
    { name: "Campañas", value: "ELEVADO", level: 48, tone: "info", note: "1 sobre presión · 2 dentro de banda" },
    { name: "Fraude", value: "BAJO", level: 12, tone: "ok", note: "Sin patrones detectados · 1 monitor activo" },
    { name: "Sitio / CX", value: "MEDIO", level: 41, tone: "info", note: "Bug iOS checkout · 38 sesiones" },
  ],

  alerts: [
    { sev: "crit", txt: "HOODIE-BLK-M cayó por debajo de 10 u. en MAD", src: "inventario.snapshot", time: "00:11", isNew: true },
    { sev: "crit", txt: "VIP M. Vázquez sin respuesta · ticket #4821", src: "soporte.snapshot", time: "00:42", isNew: true },
    { sev: "hot", txt: "CMP-778 gasto +14× sobre baseline", src: "campañas.monitor", time: "01:08", isNew: true },
    { sev: "hot", txt: "23 envíos express en riesgo de SLA", src: "logistica.cola", time: "01:32" },
    { sev: "info", txt: "Acción #6 creada · bug checkout iOS", src: "ai.acciones", time: "02:01" },
    { sev: "ok", txt: "Acción #10 reconocida y resuelta", src: "ai.acciones", time: "02:08" },
    { sev: "info", txt: "Snapshot enviado a Telegram", src: "telegram.bridge", time: "02:14" },
    { sev: "hot", txt: "CTR de CMP-651 cayó 38% última hora", src: "campañas.monitor", time: "02:22" },
    { sev: "info", txt: "Escaneo de bots iniciado para PANT-NVY-32", src: "fraude.monitor", time: "02:28" },
    { sev: "ok", txt: "BAG-ECR-OS restock recibido · 28 u.", src: "inventario.snapshot", time: "02:34" },
    { sev: "info", txt: "10 acciones priorizadas para T+02:30", src: "ai.acciones", time: "02:36" },
  ],

  orders: [
    { id: "ORD-19483", customer: "M. Vázquez", vip: true, sku: "HOODIE-BLK-M", city: "Madrid", ship: "Express", status: "Retrasado", risk: 92, reason: "VIP · SLA incumplido · ticket abierto" },
    { id: "ORD-19501", customer: "L. Ortega", vip: false, sku: "TEE-CRM-L", city: "Madrid", ship: "Express", status: "Pendiente", risk: 81, reason: "Stock bajo · cola fulfillment" },
    { id: "ORD-19510", customer: "J. Ferrer", vip: true, sku: "PANT-NVY-32", city: "Barcelona", ship: "Estándar", status: "Pendiente", risk: 76, reason: "VIP · SKU bajo monitoreo" },
    { id: "ORD-19518", customer: "S. Bauer", vip: false, sku: "HOODIE-BLK-M", city: "Madrid", ship: "Express", status: "Pendiente", risk: 74, reason: "SKU crítico · agotándose" },
    { id: "ORD-19524", customer: "A. Linares", vip: true, sku: "BAG-ECR-OS", city: "Valencia", ship: "Express", status: "Resuelto", risk: 22, reason: "Restock confirmado" },
    { id: "ORD-19528", customer: "R. Maoz", vip: false, sku: "TEE-CRM-L", city: "Madrid", ship: "Express", status: "Pendiente", risk: 71, reason: "Stock bajo" },
    { id: "ORD-19533", customer: "K. Aoki", vip: true, sku: "HOODIE-BLK-M", city: "Madrid", ship: "Estándar", status: "Pendiente", risk: 68, reason: "VIP · stock crítico" },
    { id: "ORD-19541", customer: "P. Calvo", vip: false, sku: "PANT-NVY-32", city: "Madrid", ship: "Express", status: "Pendiente", risk: 58, reason: "Carrier saturado" },
    { id: "ORD-19549", customer: "I. Sender", vip: false, sku: "TEE-CRM-L", city: "Sevilla", ship: "Estándar", status: "Pendiente", risk: 41, reason: "SKU presionado" },
    { id: "ORD-19555", customer: "F. Tinoco", vip: false, sku: "BAG-ECR-OS", city: "Bilbao", ship: "Estándar", status: "Confirmado", risk: 18, reason: "Restock OK" },
  ],

  inventory: [
    { sku: "HOODIE-BLK-M", name: "Hoodie Black", stock: 7, eta: "—", through: 92, views: 4120, cvr: "8.4%", camp: 5, h: 5 },
    { sku: "HOODIE-BLK-L", name: "Hoodie Black", stock: 22, eta: "—", through: 71, views: 3640, cvr: "5.2%", camp: 3, h: 3 },
    { sku: "TEE-CRM-L", name: "Tee Cream", stock: 18, eta: "—", through: 88, views: 2810, cvr: "6.1%", camp: 2, h: 4 },
    { sku: "TEE-CRM-M", name: "Tee Cream", stock: 41, eta: "—", through: 64, views: 2540, cvr: "4.8%", camp: 2, h: 2 },
    { sku: "PANT-NVY-32", name: "Pant Navy", stock: 38, eta: "T+04:00", through: 58, views: 1890, cvr: "8.7%", camp: 1, h: 3 },
    { sku: "PANT-NVY-30", name: "Pant Navy", stock: 62, eta: "—", through: 41, views: 1620, cvr: "3.4%", camp: 1, h: 1 },
    { sku: "BAG-ECR-OS", name: "Bag Ecru", stock: 28, eta: "T+05:30", through: 38, views: 980, cvr: "5.0%", camp: 0, h: 1 },
    { sku: "CAP-BLK-OS", name: "Cap Black", stock: 84, eta: "—", through: 24, views: 740, cvr: "3.1%", camp: 0, h: 0 },
  ],
};
